package cz.cvut.fel.aui.rules;

import cz.cvut.fel.aui.model.context.Age;
import cz.cvut.fel.aui.model.context.Device;
import cz.cvut.fel.aui.model.context.ScreenSize;
import java.util.List
import java.util.Locale
import java.awt.ComponentOrientation;

global java.util.Map env;


rule "RULE 5: Country" when
    cz.cvut.fel.aui.model.Context($country:country)
then
    env.put("country",$country);
end



rule "RULE 7: Show data as list" when
    cz.cvut.fel.aui.model.Context(device != Device.DESKTOP)
then
    env.put("table","list");
end



rule "RULE 8a: Locale" when
    cz.cvut.fel.aui.model.Context($language:language, $country:country)
then
    Locale locale = new Locale($language, $country);
    env.put("locale", new Locale($language, $country));
    insert(locale);
end



rule "RULE 8b: Right to left" when
    $locale: Locale()
then
    env.put("RTL",!ComponentOrientation.getOrientation($locale).isLeftToRight());
end



rule "RULE 6a: Mobile interface" when
    cz.cvut.fel.aui.model.Context(device != Device.DESKTOP || screenSize == ScreenSize.small)
then
    env.put("layout","mobile");
end

rule "One column layout" when
	cz.cvut.fel.aui.model.Context(screenSize == ScreenSize.normal)
then
	env.put("layout", "oneColumn");
end


rule "RULE 1: Graphic ui" when
    cz.cvut.fel.aui.model.Context(age == Age.CHILD)
then
    env.put("applyImage",true);
end



rule "RULE 2: Help" when
    cz.cvut.fel.aui.model.Context(age == Age.ELDER || invalid > 2)
then
    env.put("applyHelp",true);
end



rule "RULE 3: AspectFaces roles" when
    cz.cvut.fel.aui.model.Context($age:age)
    ctx: com.codingcrayons.aspectfaces.configuration.Context()
then
    ctx.setRoles(new String[]{$age.name().toLowerCase()});
end



rule "RULE 4: AspectFaces profile COUNTRY_%" when
    cz.cvut.fel.aui.model.Context($country:country)
    ctx: com.codingcrayons.aspectfaces.configuration.Context()
then
    ctx.setProfiles(new String[]{"COUNTRY_"+$country});
end



rule "RULE 6b: AspectFaces mobile layout" when
    cz.cvut.fel.aui.model.Context(device != Device.DESKTOP)
    ctx: com.codingcrayons.aspectfaces.configuration.Context()
then
    ctx.setLayout("mobile");
end